<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{38e7ac3d-a4b5-4c4e-904d-27c6290e435e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MyBoolean : BOOL;
	MyBoolean_2 : BOOL;
	MyBoolean_3 : BOOL;
	
	iValue1 : DINT := 20;
	iValue2 : DINT;
	
	sMyString : STRING;
	sMyNumString : STRING[255];
	
	i_Num_from_arr : DINT;
	i_len_arr_B : INT;
	arr_A : ARRAY [0..10] OF DINT;
	arr_B : ARRAY [0..4] OF DINT :=[20, 40, 60 ,80, 100];
	// timers
	fb_My_timer : TON;
	// tiggers
	fb_my_trigger : R_TRIG; // Counter 
	
	// Timer
	fb_MI1_Timer_Increase_Speed: TON;
END_VAR

VAR_OUTPUT
END_VAR

	

]]></Declaration>
    <Implementation>
      <ST><![CDATA[















]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="160" Count="13" />
      <LineId Id="74" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="57" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>