<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{0829745f-6756-489d-bf06-f977de883d65}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MyBoolean : BOOL;
	MyBoolean_2: BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>